spring:
  application:
    name: content-service

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/content_db?authSource=admin

server:
  port: 8084
  servlet:
    context-path: /content-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

reactor:
  netty:
    threads: 200

cloudinary:
  cloud_name: dm1alq68q
  api_key: 392714169722963
  api_secret: 78opY4-nD40-VZbYTqDsU_tDPMc

logging:
  level:
    com.learning.content_service: DEBUG
    org.springframework.graphql: DEBUG


app:
  services:
    course:
      url: http://localhost:8082/course-service
jwt:
  secret: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"