spring:
  application:
    name: content-service

  data:
    mongodb:
      authentication-database: admin
      database: content_db
      host: localhost
      port: 27017

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#reactive webflux streaming
reactor:
  netty:
    threads: 200

cloudinary:
  cloud_name: dm1alq68q
  api_key: 392714169722963
  api_secret: 78opY4-nD40-VZbYTqDsU_tDPMc

logging:
  level:
    com.learning.content_service: DEBUG
    org.springframework.graphql: DEBUG